export const applogo = require('./AppLogo.png');
export const cancel = require('./x.png');
export const colourPrediction = require('./colorPrediction.webp');
export const FooterWallet = require('./FooterImage.webp');
export const sameClock = require('./clockNew.webp');
export const lefArrow = require('./leftArrow.png');
export const headerWallet = require('./wallet.png');
// export const splashScreen = require('./newSplash.png');
export const splashScreen = require('./splashNew.png');
export const refer = require('./refer.jpg');
export const banner1 = require('./Banner/banner1.jpg');
export const banner2 = require('./Banner/banner2.jpg');
export const banner3 = require('./Banner/banner3.jpg');
export const banner4 = require('./Banner/banner4.jpg');
export const gifAgent = require('./Agent.gif');
export const gifRefer = require('./Referfriend.gif');
export const gifLottery = require('./Lottery.gif');
export const gifPromotion = require('./promotion.webp');
export const DearLotteryImage = require('./3DigitHomeImage/DearLotteryImage.webp');
export const KeralaLotteryImage = require('./3DigitHomeImage/KeralaLotteryImage.webp');
export const KubberLotteryImage = require('./3DigitHomeImage/KubberLotteryImage.webp');
export const LucwinImage = require('./3DigitHomeImage/LucwinImage.webp');
export const Quick3DImage = require('./3DigitHomeImage/Quick3DImage.webp');
export const ActiveTabBg = require('./Home/ActiveTabBackground.webp');
export const ActiveTabInitialImg = require('./Home/ActiveTab.webp');
export const bhutan = require('./3DigitHomeImage/bhutan.webp');
// export const chennaiLottery = require('./3DigitHomeImage/chennaiLottery.webp');
export const quick3min = require('./3DigitHomeImage/quick3min.webp');
export const skywin = require('./3DigitHomeImage/skywin.webp');
export const wallet = require('./ProfileScreen/wallet3DImage.webp');
export const gift = require('./ProfileScreen/gift.png'); 
export const transfer = require('./ProfileScreen/transactionIcon.png'); 
export const myBets = require('./ProfileScreen/myBets.png');  
export const rebate = require('./ProfileScreen/rebate.png'); 
export const myTransaction = require('./ProfileScreen/Mytransactions.jpg'); 
export const notification = require('./ProfileScreen/notificationIcon.jpg'); 
export const customerService = require('./ProfileScreen/CustomerServiceIcon.jpg');
export const customerServiceTopIcon = require('./ProfileScreen/customerService.png');
export const leftArrowHeader = require('./ProfileScreen/leftArrowHeader.png');
export const backGround = require('./ProfileScreen/testBG.jpg');
export const backGround1 = require('./ProfileScreen/testBG1.jpeg');
export const addIcon = require('./ProfileScreen/plus_add_green.webp');
export const cardImageBG = require('./ProfileScreen/try.jpg');
export const profileLotteriesImage = require('./ProfileScreen/lotteriesNew.webp');
export const profileCommissionImage = require('./ProfileScreen/Commission.webp');
export const profileTransactionImage = require('./ProfileScreen/Transactions.webp');
export const profileCustomerServiceImage = require('./ProfileScreen/Service.webp');
export const profileTwentyFourImage = require('./ProfileScreen/24-7-PNG-Image.png');
export const profileTwentyFourImage1 = require('./ProfileScreen/twentyFourSeven.png');
export const loginImageBackground = require('./ProfileScreen/LoginImageBackground.webp'); 
export const casino = require('./Home/casino.webp')
export const lottery1 = require('./Home/lottery.webp');
export const scratch = require('./Home/scratch.webp');
export const sports = require('./Home/sports.webp');
export const rummy = require('./Home/rummy.webp');
export const gameTypeAct = require("./Home/gameTypeAct.webp")
export const hot = require('./Casino/huo.gif')
export const pg = require('./Casino/PG.webp')
export const jdb = require('./Casino/JDB.webp')
export const Jili = require('./Casino/JILI.webp')
export const dragonvsTiger = require('./Casino/dragonTiger.webp')
export const threePatti = require('./Casino/threePatti.webp')
export const teenPatti = require('./Casino/teenPatti.webp')
export const sevenUpAndDown = require('./Casino/sevenUpAndDown.webp')
export const digit = require('./LotteryImages/3d.webp')
export const color = require('./LotteryImages/color.webp')
export const dice = require('./LotteryImages/dice.webp')
export const lotteryHeader = require('./LotteryImages/lotteryHeader.webp')
export const chipIcon = require('./tab-title-icon.webp')
export const walletIcon = require('./wallet-icon.webp')
export const refreshIcon = require('./refreshIcon.webp')
export const CustomerServiceIcon = require('./customer-service.webp')
export const signInLogo = require('./ProfileScreen/singinLogo.webp')
export const signInCustomerLogo = require('./ProfileScreen/signInCustomer.webp')
export const referral = require('./ProfileScreen/referralCodeImage.webp')
export const tootTipImage = require('./ProfileScreen/tooltipImage.webp')
export const bannerLuna1 = require('./Home/sliderImageLunaNew.webp');
export const bannerLuna2 = require('./Home/SliderImageLunaNew1.webp')
export const walletMini = require('./walletMini.webp')
export const refresh = require('./refershImage.webp')
export const checkBox = require('./checkboxImg.webp')
export const rebateMenu = require('./Drawer/rebateMenu.webp')
export const bigSpin = require('./Drawer/big-spin.webp')
export const robMoney = require('./Drawer/robMoney.webp')
export const freeLottery = require('./Drawer/free-lottery.webp')
export const quick3dMenu = require('./Drawer/quick3dMenu.webp')
export const digitMenu = require('./Drawer/3dMenu.webp')
export const casinMenu = require('./Drawer/casinoMenu.webp')
export const scratchMenu = require('./Drawer/scratchMenu.webp')
export const sportMenu = require('./Drawer/sportMenu.webp')
export const superAgent = require('./Drawer/super-agent.webp')
export const promotions = require('./Drawer/promotions.webp')
export const homeTab = require('./BottomTabs/homeTab.webp')
export const homeNewIcon = require('./BottomTabs/HomeIconUpdated.png')
export const homeNewIconSilver = require('./BottomTabs/HomeIconSilver.png')
export const promotionNewIcon = require('./BottomTabs/PromotionUpdated.png')
export const inviteNewIcon = require('./BottomTabs/EarnMoney.png')
export const resultNewIcon = require('./BottomTabs/ResultsUpdated.png')
export const meNewIcon = require('./BottomTabs/MeiconUpdated.png')
export const casinoTab = require('./BottomTabs/casinoTab.webp')
export const inviteTab = require('./BottomTabs/inviteTab.webp')
export const resultTab = require('./BottomTabs/resultTab.webp')
export const meTab = require('./BottomTabs/meTab.webp')
export const homeActiveTab = require('./BottomTabs/home-active.webp')
export const casinoActiveTab = require('./BottomTabs/casino-active.webp')
export const inviteActiveTab = require('./BottomTabs/invite-active.webp')
export const resultActiveTab = require('./BottomTabs/result-active.webp')
export const meActiveTab = require('./BottomTabs/me-active.webp')
export const checked = require('./checked.webp')
export const unchecked = require('./un-checked.webp')
export const close = require('./ProfileScreen/close.webp')
export const vipBorder = require('./ProfileScreen/goldBorder.png')
export const vipBadgeZero = require('./ProfileScreen/walletLevelImage.webp')
export const levelZeroBadge = require('./ProfileScreen/level0.webp')
export const levelOneBadge = require('./ProfileScreen/level1.webp')
export const levelTwoBadge = require('./ProfileScreen/level2.webp')
export const levelThreeBadge = require('./ProfileScreen/level3.webp')
export const levelFourBadge = require('./ProfileScreen/level4.webp')
export const levelFiveBadge = require('./ProfileScreen/level5.webp')
export const levelSixBadge = require('./ProfileScreen/level6.webp')
export const levelSevenBadge = require('./ProfileScreen/level7.webp')
export const levelEightBadge = require('./ProfileScreen/level8.webp')
export const levelNineBadge = require('./ProfileScreen/level9.webp')
export const bonusCash = require('./ProfileScreen/BonusCash.webp')
export const spin = require('./ProfileScreen/luckSpin.webp')
export const rechargeIconCard = require('./recharge-iconCard.webp')
export const betIconCard = require('./bet-icon.webp')
export const rupeeCoinLoaderGif = require('./RupeeCoin.gif')
export const amountIcon = require('./Home/amount.webp')
export const homeAppIcon = require('./Home/ft.webp')
export const hIcon = require('./Home/side.webp')
export const drawerLevel = require('./Drawer/drawerLevel.webp')
export const drawerHeader = require('./Drawer/drawerHeader.webp')
export const invitetop = require('./InviteScreen/invitetop.webp')
export const graphIcon= require('./InviteScreen/graph-icon.webp')
export const CommissionIcon= require('./InviteScreen/commision.webp')
export const inviteRecharge= require('./InviteScreen/inviteRecharge.webp')
export const wallet3dImage1 = require('./ProfileScreen/wallet3dImage1.webp')

export const oneMin3DImage = require('./LotteryImages/1min3D.png')
export const threeMin3DImage = require('./LotteryImages/3min3D.png')
export const fiveMin3DImage = require('./LotteryImages/5min3D.png')

// Quick 3D menu (new images)
export const quick3d1min = require('./quick3dImages/quick3d1min.png')
export const quick3d3min = require('./quick3dImages/quick3d3min.png')
export const quick3d5min = require('./quick3dImages/quick3d5min.png')
export const quick1 = require('./quick3dImages/1.jpg')
export const quick2 = require('./quick3dImages/2.jpg')
export const quick3 = require('./quick3dImages/3.jpg')
// export const vipBadgeBackground = require('./vipBadgeBackground.webp')
export const vipBadgeBackground = require('./vipBadgeBackground.png')
export const greenTick = require('./greenTick.png')
export const noDataImage = require('./no-data.webp')
export const betAlertImage = require('./warning.png') 
// export const winLabel = require('./winLabel.webp') 
export const winLabel = require('./newWinLabel.png') 
export const myOrdersWinLabel = require('./myOrder-win-bg.webp')
export const copyImage = require('./copy.webp')
export const newSplashScreen = require('./AnnaiSplash.jpg') 
export const inviteHero = require('./InviteScreen/inviteHero.png')
export const rightTime = require('./InviteScreen/rightTime.webp')
export const agentLevels = require('./InviteScreen/agentLevels.webp')
export const comeBackBanner = require('./Promotions/comeBackBonus.jpg')
export const insideBannerComeBack = require('./Promotions/comebackinsidebanner.png')
export const megaRechargeBonus = require('./Promotions/megaRechargeBonus.jpg')
export const insideBannerMegaRecharge = require('./Promotions/MegaRechargeinsidebanner.png')
export const vipWeeklySalary = require('./Promotions/vipWeeklySalary.jpg')
export const insideBannerVip = require('./Promotions/vipweeklysalaryinsidebanner.png')
export const promotionBanner4 = require('./Promotions/promotionBanner4.jpg')
export const threeDigitBettingBonus = require('./Promotions/3DigitBettingBonus.jpg')
export const insideBannerThreeDigit = require('./Promotions/3DigitBettingInsideBonus.png')
export const agentBonus = require('./Promotions/AgentBonus.jpg')
export const insideBannerAgent = require('./Promotions/AgentBonusinsidebanner.png')
export const attendanceBonus = require('./Promotions/AttendanceBonus.jpg')
export const insideAttendanceBonus = require('./Promotions/AttendancebonusInsidebanner.png')

export const annaiBanner = require('./Home/annaiBanner.png')
export const annaiBanner1 = require('./Home/annaiBanner1.png')
export const annaiIcon = require('./icon.png')
export const newRebateLogo = require('./rebate.png') 
export const agentRecharge = require('./agentRechargeIcon.png') 
export const agentNewUsers = require('./add-group.png')
export const agentActiveUser = require('./active-user.png') 
export const agentRechargeMonth = require('./wallet(1).png')
export const agentCommission = require('./commission(2).png') 
export const resetIcon = require('./resetNew.png')
// export const multiUserIcon = require('./BottomTabs/multiUser.png')
export const multiUserIcon = require('./BottomTabs/multi.png')

// Leaderboard
export const leaderboardHeading = require('./leaderBoard/leaderboardheading.png')
export const leaderboardFireworks = require('./leaderBoard/fireworks.png')
export const leaderboardFirst = require('./leaderBoard/1.png')
export const leaderboardSecond = require('./leaderBoard/2.png')
export const leaderboardThird = require('./leaderBoard/3.png')

// Recent Winners (same folder as leaderBoard)
export const recentWinnersHeading = require('./leaderBoard/Recentwinnersheading.png')
// Home logo
export const homeIcon = require('./Home/logo.png')


// new bannerImages 


export const bannerWhatsapp = require('./Home/joinWhatsapp.webp')
export const bannerTelegram = require('./Home/JOINANNAILOTTERY.webp')
export const bannerliveCasionoGames = require('./Home/LIVECASINOANNAILOT.webp')
export const bannerColorGames = require('./Home/colorgameannai.webp')
export const bannerDiceGames = require('./Home/diceannai.webp')
// export const newLogo = require('./Home/newAnnaiHomeLogo.png')
export const newLogo = require('./Home/a.png')
export const newHomeWallet = require('./Home/newHomeWallet.webp')
export const newHomeWallet1 = require('./Home/newWallet1.png')
export const offerImage1 = require('./Home/OfferImage1.png')
export const offerImage2 = require('./Home/OfferImage2.png')
export const Durga = require('./Home/Durga.jpeg')
export const AnnaPoorna = require('./Home/AnnaPoorna.jpeg')
export const signInMain = require('./signinTopImage.jpeg')
export const signInLogoNew = require('./ProfileScreen/siginLogoNew.png')
export const signInLogoNew1 = require('./ProfileScreen/signInLogoBlue.png')
export const signInLogoNew2 = require('./ProfileScreen/logoA.png')
export const vipNewLogoZero = require('./ProfileScreen/vipNewBadge0.png')
export const vipNewLogoOne = require('./ProfileScreen/vipNewBadge1.png')
export const vipNewLogoTwo = require('./ProfileScreen/vipNewBadge2.png')
export const vipNewLogoThree = require('./ProfileScreen/vipNewBadge3.png')
export const vipNewLogoFour = require('./ProfileScreen/vipNewBadge4.png')
export const vipNewLogoFive = require('./ProfileScreen/vipNewBadge5.png')
export const vipNewLogoSix = require('./ProfileScreen/vipNewBadge6.png')
export const vipNewLogoSeven = require('./ProfileScreen/vipNewBadge7.png')
export const vipNewLogoEight = require('./ProfileScreen/vipNewBadge8.png')
export const vipNewLogoNine = require('./ProfileScreen/vipNewBadge9.png')
export const vipNewLogoTen = require('./ProfileScreen/vipNewBadge10.png')
export const vipNewLogoEleven = require('./ProfileScreen/vipNewBadge11.png')
export const vipNewLogoTwelve = require('./ProfileScreen/vipNewBadge12.png')
export const vipNewLogoThirteen = require('./ProfileScreen/vipNewBadge13.png')
export const vipNewLogoFourteen = require('./ProfileScreen/vipNewBadge14.png')
export const vipNewLogoFifteen = require('./ProfileScreen/vipNewBadge15.png')
export const DrawerRebate = require('./DrawerRebate.png')
export const DrawerPromotion = require('./DrawerPromotion.png')
export const DrawerSuperAgent = require('./DrawerSuperAgent.png')

// Avatars

export const avatar1 = require('./Home/Avatar/Avatar1.jpg')
export const avatar2 = require('./Home/Avatar/Avatar2.jpg')
export const avatar3 = require('./Home/Avatar/Avatar3.jpg')
export const avatar4 = require('./Home/Avatar/Avatar4.jpg')
export const avatar5 = require('./Home/Avatar/Avatar5.jpg')
export const avatar6 = require('./Home/Avatar/Avatar6.jpg')
export const avatar7 = require('./Home/Avatar/Avatar7.jpg')
export const avatar8 = require('./Home/Avatar/Avatar8.jpg')
export const avatar9 = require('./Home/Avatar/Avatar9.jpg')
export const avatar10 = require('./Home/Avatar/Avatar10.jpg')
export const avatar11 = require('./Home/Avatar/Avatar11.jpg')
export const avatar12 = require('./Home/Avatar/Avatar12.jpg')

// Recent Winners
export const rw1 = require('./Home/RecentWinner/RW1.webp')
export const rw2 = require('./Home/RecentWinner/RW2.jpg')
export const rw3 = require('./Home/RecentWinner/RW3.jpeg')
export const rw4 = require('./Home/RecentWinner/RW4.avif')
export const rw5 = require('./Home/RecentWinner/RW5.avif')
export const rw6 = require('./Home/RecentWinner/RW6.jpg')
